version: "3.9"

x-base-versions: &base-versions
  NODE_MAJOR: "18"

services:
  nestjs-service: &nestjs-service
    build:
      context: .
      dockerfile: Dockerfile
      args: *base-versions
    tmpfs:
      - /tmp:exec,mode=777
    stdin_open: true
    env_file: .env
    volumes:
      - .:/nestjs-app:cached
      - node_modules:/nestjs-app/node_modules
      - dist:/nestjs-app/dist
    depends_on:
      - redis-dev

  shell:
    <<: *nestjs-service
    command: /bin/bash

  nestjs-dev:
    <<: *nestjs-service
    command: npm run start:dev
    ports:
      - "${PORT}:${PORT}"

  vscode:
    <<: *nestjs-service
    command: /bin/sh -c "while sleep 1000; do :; done"

  redis-dev:
    image: redis:alpine
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis-dev:/data
    tmpfs:
      - /tmp

volumes:
  redis-dev:
  node_modules:
  dist:
